### ISSUE TITLE
Issue for another repo

### ISSUE THREAD

**Issue by rhythm-appyhigh** [manavm1990/vite-react-tailwind-vitest#1]
I know this is not the right place for this issue, but one of your template has a major issue, which in my opinion should be addressed.

I just cloned the repo
https://github.com/manavm1990/next-app-router-tailwind-mui-starter

and to my surprise, seems like you forgot to add @mui dependencies in package.json which breaks everything. If possible please check that out and maybe update it also

**Comment by manavm1990** [comment]
That repo has been archived and is not intended for use. I'm glad that you found the solution and hopefully it helped somehow.
